package fr.y0annd.boutique.app.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class BackgroundTaskController {
	@FXML
	private Button btnActiver;
	@FXML
	private Label lblTache1;
	@FXML
	private Button btnInterromre;
	@FXML
	private Label lblTache2;

	// Event Listener on Button[#btnActiver].onAction
	@FXML
	public void onActivate(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnInterromre].onAction
	@FXML
	public void onCancel(ActionEvent event) {
		// TODO Autogenerated
	}
}
