package fr.y0annd.boutique.app.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;

public class WebController {
	@FXML
	private Button previousBtn;
	@FXML
	private Button nextBtn;
	@FXML
	private TextField urlTxt;
	@FXML
	private Button goBtn;
	@FXML
	private Button statsBtn;

	// Event Listener on Button[#previousBtn].onAction
	@FXML
	public void onPrevious(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#nextBtn].onAction
	@FXML
	public void onNext(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#goBtn].onAction
	@FXML
	public void onGo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#statsBtn].onAction
	@FXML
	public void onStats(ActionEvent event) {
		// TODO Autogenerated
	}
}
