package fr.y0annd.boutique.app.controller;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.web.WebHistory;
import javafx.scene.web.WebView;

public class WebController implements Initializable {
	@FXML
	private WebView webView;
	@FXML
	private Button previousBtn;
	@FXML
	private Button nextBtn;
	@FXML
	private TextField urlTxt;
	@FXML
	private Button goBtn;
	@FXML
	private Button statsBtn;

	// Event Listener on Button[#previousBtn].onAction
	@FXML
	public void onPrevious(ActionEvent event) {
		WebHistory history = webView.getEngine().getHistory();
		history.go(-1);
		urlTxt.setText(history.getEntries().get(history.getCurrentIndex()).getUrl());

	}

	// Event Listener on Button[#nextBtn].onAction
	@FXML
	public void onNext(ActionEvent event) {
		WebHistory history = webView.getEngine().getHistory();
		history.go(1);
		urlTxt.setText(history.getEntries().get(history.getCurrentIndex()).getUrl());

	}

	// Event Listener on Button[#goBtn].onAction
	@FXML
	public void onGo(ActionEvent event) {
		System.out.println("Go to: " + urlTxt.getText());
		URL url = null;
		try {
			url = new URL(urlTxt.getText());
			webView.getEngine().load(url.toString());
		} catch (MalformedURLException e) {
			System.err.println("L'URL est incorrecte");
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#statsBtn].onAction
	@FXML
	public void onStats(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
//		nextBtn.disableProperty().bind(webView.getEngine().getHistory().currentIndexProperty()
//				.lessThan(webView.getEngine().getHistory().getEntries().size()));
		previousBtn.disableProperty().bind(webView.getEngine().getHistory().currentIndexProperty().isEqualTo(0));
	}
}
